export const towns = [
  "all",
  "Sengkang",
  "Punggol",
  "Woodlands",
  "Yishun",
  "Tampines",
  "Jurong West",
  "Bedok",
  "Hougang",
  "Choa Chu Kang",
  "Bukit Batok",
  "Ang Mo Kio",
  "Bukit Merah",
  "Bukit Panjang",
  "Toa Payoh",
  "Kallang/Whampoa",
  "Sembawang",
  "Pasir Ris",
  "Queenstown",
  "Geylang",
  "Clementi",
  "Jurong East",
  "Serangoon",
  "Bishan",
  "Central Area",
  "Marine Parade",
  "Bukit Timah",
];
