import { Property } from "@/type";

export const dummyProperties: Property[] = [
  {
    id: 1,
    title: "Spacious 4-Room HDB in Prime Jurong West",
    imageUrl: "https://picsum.photos/400/300?random=1",
    town: "Jurong West",
    flatType: "4-Room",
    price: 600_000,
    size: 95,
    bedrooms: 3,
    bathrooms: 2,
    carpark: true,
    floor: "10-12",
    builtYear: 2010,
    views: 234,
    agent: {
      name: "Sarah Lim",
      phone: "+65 9123 4567",
      avatar: "https://i.pravatar.cc/40?img=1",
    },
  },
  {
    id: 2,
    title: "Modern 5-Room HDB with Panoramic View",
    imageUrl: "https://picsum.photos/400/300?random=2",
    town: "Tampines",
    flatType: "5-Room",
    price: 850_000,
    size: 110,
    bedrooms: 4,
    bathrooms: 2,
    carpark: true,
    floor: "15-17",
    builtYear: 2015,
    views: 187,
    agent: {
      name: "David Tan",
      phone: "+65 9234 5678",
      avatar: "https://i.pravatar.cc/40?img=2",
    },
  },
  {
    id: 3,
    title: "Cozy 3-Room HDB Near MRT Station",
    imageUrl: "https://picsum.photos/400/300?random=3",
    town: "Toa Payoh",
    flatType: "3-Room",
    price: 450_000,
    size: 75,
    bedrooms: 2,
    bathrooms: 1,
    carpark: false,
    floor: "5-7",
    builtYear: 2005,
    views: 156,
    agent: {
      name: "Michelle Wong",
      phone: "+65 9345 6789",
      avatar: "https://i.pravatar.cc/40?img=3",
    },
  },
  {
    id: 4,
    title: "Renovated 4-Room HDB with Modern Fittings",
    imageUrl: "https://picsum.photos/400/300?random=4",
    town: "Bishan",
    flatType: "4-Room",
    price: 720_000,
    size: 92,
    bedrooms: 3,
    bathrooms: 2,
    carpark: true,
    floor: "8-10",
    builtYear: 2008,
    views: 298,
    agent: {
      name: "Kevin Loh",
      phone: "+65 9456 7890",
      avatar: "https://i.pravatar.cc/40?img=4",
    },
  },
  {
    id: 5,
    title: "Executive Maisonette with Garden View",
    imageUrl: "https://picsum.photos/400/300?random=5",
    town: "Ang Mo Kio",
    flatType: "Executive",
    price: 950_000,
    size: 135,
    bedrooms: 4,
    bathrooms: 3,
    carpark: true,
    floor: "1-3",
    builtYear: 2012,
    views: 342,
    agent: {
      name: "Rachel Ng",
      phone: "+65 9567 8901",
      avatar: "https://i.pravatar.cc/40?img=5",
    },
  },
  {
    id: 6,
    title: "Bright 3-Room HDB with Open Concept",
    imageUrl: "https://picsum.photos/400/300?random=6",
    town: "Hougang",
    flatType: "3-Room",
    price: 380_000,
    size: 68,
    bedrooms: 2,
    bathrooms: 1,
    carpark: true,
    floor: "3-5",
    builtYear: 2000,
    views: 123,
    agent: {
      name: "James Koh",
      phone: "+65 9678 9012",
      avatar: "https://i.pravatar.cc/40?img=6",
    },
  },
  {
    id: 7,
    title: "Premium 5-Room HDB in Central Location",
    imageUrl: "https://picsum.photos/400/300?random=7",
    town: "Clementi",
    flatType: "5-Room",
    price: 890_000,
    size: 115,
    bedrooms: 4,
    bathrooms: 2,
    carpark: true,
    floor: "12-14",
    builtYear: 2018,
    views: 267,
    agent: {
      name: "Grace Lee",
      phone: "+65 9789 0123",
      avatar: "https://i.pravatar.cc/40?img=7",
    },
  },
  {
    id: 8,
    title: "Well-Maintained 4-Room HDB with Amenities",
    imageUrl: "https://picsum.photos/400/300?random=8",
    town: "Woodlands",
    flatType: "4-Room",
    price: 580_000,
    size: 88,
    bedrooms: 3,
    bathrooms: 2,
    carpark: true,
    floor: "6-8",
    builtYear: 2007,
    views: 189,
    agent: {
      name: "Anthony Lim",
      phone: "+65 9890 1234",
      avatar: "https://i.pravatar.cc/40?img=8",
    },
  },
  {
    id: 9,
    title: "Stunning 5-Room Corner Unit with Sea View",
    imageUrl: "https://picsum.photos/400/300?random=9",
    town: "Marine Parade",
    flatType: "5-Room",
    price: 1_200_000,
    size: 120,
    bedrooms: 4,
    bathrooms: 2,
    carpark: true,
    floor: "18-20",
    builtYear: 2019,
    views: 445,
    agent: {
      name: "Helen Tay",
      phone: "+65 9001 2345",
      avatar: "https://i.pravatar.cc/40?img=9",
    },
  },
  {
    id: 10,
    title: "Charming 3-Room HDB in Heritage District",
    imageUrl: "https://picsum.photos/400/300?random=10",
    town: "Tiong Bahru",
    flatType: "3-Room",
    price: 520_000,
    size: 70,
    bedrooms: 2,
    bathrooms: 1,
    carpark: false,
    floor: "4-6",
    builtYear: 1995,
    views: 203,
    agent: {
      name: "Peter Goh",
      phone: "+65 9112 3456",
      avatar: "https://i.pravatar.cc/40?img=10",
    },
  },
];
